### ISSUE TITLE
Editing a Department produces the following error “The value 'System.Byte[]' is not valid for RowVersion.”

### ISSUE THREAD

**Issue by bobgodfrey** [jbogard/ContosoUniversityDotNetCore-Pages#14]
It look like the HtmlConventionRegistry setup or the HtmlTags.AspNetCore library has a problem.   It looks like you are trying to override the output format of a timestamp/rowversion in the HtmlConventionRegistry setup but it’s not working.   The following code produces the hidden input at the bottom.  As you can see the value is "System.Byte[]" and not getting converted to the base64 string.
 You can reproduce this issue if you edit and try to save one of the Departments.

Editors.IfPropertyIs<byte[]>().BuildBy(a => new HiddenTag().Value(Convert.ToBase64String(a.Value<byte[]>())));

input type="hidden" value="System.Byte[]" name="Data.RowVersion" id="Data_RowVersion" class="form-control"

**Comment by jbogard** [comment]
This is because you need to use a modifier, not a builder. Builders create the HtmlTag, then modifiers add attributes. The value part gets set with a modifier, so you need Build and Modify.
