### ISSUE TITLE
Integration tests: Parallelism and EF migrations

### ISSUE THREAD

**Issue by Rookian** [jbogard/ContosoUniversityDotNetCore-Pages#16]
I noticed some things regarding the integration tests.

As far as I can see the tests run in parallel. 
Is that by purpose?
**Solutions**: Using `Collection `Attribute or `[assembly: CollectionBehavior(DisableTestParallelization = true)]`

I could not find anything about migrating the database by using EF migrations?
Do you run them once before executing the tests? In a build script that would be fine, but running tests within VS would be a bit of a pain to migrate the db manually before executing tests.

**Comment by jbogard** [comment]
Yeah I wanted to enable it. And I don't use EF migrations, each tests' data is independent. I use though Respawn to wipe the database before the full run.
