### ISSUE TITLE
Fixie as testing framework instead of xUnit.

### ISSUE THREAD

**Issue by lesair** [jbogard/ContosoUniversityDotNetCore-Pages#18]
## Description
Please consider either adding a fork of this sample app that uses Fixie instead of xUnit, or adding a set of tests using Fixie.

## Justification
As mentioned in the blog post "[Integration Testing with xUnit](https://jimmybogard.com/integration-testing-with-xunit/)", referring to the infrastructure built to run integration tests with xUnit: 

> Writing tests this manner allows me to fit inside xUnit's lifecycle configuration - **but it's super ugly**.

and

> ...while it's feasible to write tests in this way, I'd suggest avoiding it... Instead, either use a framework more suited for this style of tests (**Fixie** or any of the BDD-style libraries)...

**Comment by jbogard** [comment]
No...none of my client projects use Fixie...this is intended to show what a typical project would look like.
