### ISSUE TITLE
.ConfigureAwait(false) is redundant

### ISSUE THREAD

**Issue by paulvanbladel** [jbogard/ContosoUniversityDotNetCore-Pages#2]
Hi Jimmy,

I'm far from an expert in async/await related matters but according to this article, in .Net Core ConfigureAwait(false) is redundant, apparently.

It doesn't harm, but since people see it here, they might presume that it is mandatory.

https://stackoverflow.com/questions/13489065/best-practice-to-call-configureawait-for-all-server-side-code

**Comment by jbogard** [comment]
Ah, thanks!
