### ISSUE TITLE
Unit test using the wrong database

### ISSUE THREAD

**Issue by TDK1964** [jbogard/ContosoUniversityDotNetCore-Pages#32]
Hi Jimmy, 

When running the unit tests they seem to be connecting to ContosoUniversityDotNetCore-Pages database instead of ContosoUniversityDotNetCore-Pages-Test?

Is this a know issue?

**Comment by garoyeri** [comment]
This was resolved in the switch over to using psake as the new build script. I noticed the testing csproj file was not doing the right thing. @jbogard you can close this issue.
