### ISSUE TITLE
Internal Api warning Microsoft.EntityFrameworkCore.Internal.AsyncLock

### ISSUE THREAD

**Issue by aredfox** [jbogard/ContosoUniversityDotNetCore-Pages#38]
The [example](https://github.com/jbogard/ContosoUniversityDotNetCore-Pages/blob/master/ContosoUniversity.IntegrationTests/IntegrationTestBase.cs#L18) that demonstrates the use of Respawn at has a warning on `Microsoft.EntityFrameworkCore.Internal.AsyncLock`: ` Warning EF1001: Microsoft.EntityFrameworkCore.Internal.AsyncLock is an internal API that supports the Entity Framework Core infrastructure and not subject to the same compatibility standards as public APIs. It may be changed or removed without notice in any release.
` 

How should we tackle this, or is there a better way to use this?

**Comment by jbogard** [comment]
Where are you seeing this message? I don't see any warning anywhere.

**Comment by jbogard** [comment]
That method I'm using is from the [Nito.AsyncEx](https://www.nuget.org/packages/Nito.AsyncEx) package. Maybe you're accidentally using the EF Core method instead?
