### ISSUE TITLE
Question about the transaction filter.

### ISSUE THREAD

**Issue by paulvanbladel** [jbogard/ContosoUniversityDotNetCore-Pages#4]
Hope you don't mind asking a question here.
I was wondering if the transaction filter is really necessary. As far as I know, a dbContext by default sets up a transaction?

I see a case for your approach when the mediatR commands would raise DomainEvents and where typically the code  where these domain events are handled should be part of the main transaction.

BTW, what I like about Razor Pages is that the approach is quite similar to what  Blazor will bring (https://blogs.msdn.microsoft.com/webdev/2018/03/22/get-started-building-net-web-apps-in-the-browser-with-blazor/).

**Comment by jbogard** [comment]
I don't know? In EF6 at least it was all implicit, so we added explicit transactions to make it very clear the lifecycle of a DbContext, and you don't get multiple connections. Trying to make it very obvious that a DbContext was one unit of work. So this just makes it the default behavior - you can call SaveChanges multiple times but there's just one ambient transaction.
