### ISSUE TITLE
Static test fixture vs xunit Collection Fixtures

### ISSUE THREAD

**Issue by tafs7** [jbogard/ContosoUniversityDotNetCore-Pages#42]
@jbogard  - Wanted to better understand the choice of using a static ctor on the test fixture with a bunch of static helper methods, vs. using xUnit's [Collection Fixtures](https://xunit.net/docs/shared-context#collection-fixture) to set up the environment and database.

Was this an intentional decision? If so, what are the pros/cons of either?  I am building some integration tests for a client and this is the 2nd example I've seen using this approach, so I'd like to understand the architectural decision for this approach here.

THanks!

**Comment by jbogard** [comment]
Ah, I should go back and address this, but yes, in newer client projects I use the collection fixture (even though collection fixtures are....clunky to say the least 😆 )

**Comment by jbogard** [comment]
On a side note - I do find the `using static` mechanism a bit easier to work with...

**Comment by jbogard** [comment]
Converted!
